//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CONCEPTO_TIPOFACTURA", Schema = "FACTURACION")]
    public partial class CONCEPTO_TIPOFACTURA
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal ID_CONCEPTOTIPO { get; set; }
        public decimal ID_CONCEPTO { get; set; }
        public int ID_TIPOFACTURA { get; set; }

        [ForeignKey("ID_TIPOFACTURA")]
        public virtual TIPO_FACTURA TIPO_FACTURA { get; set; }
    }
}
