//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DETALLE_FACTURA", Schema = "FACTURACION")]
    public partial class DETALLE_FACTURA
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_DETALLEFACTURA { get; set; }
        public int ID_FACTURA { get; set; }
        public Nullable<int> N_ORDEN { get; set; }
        public string S_NOMBRE { get; set; }
        public Nullable<decimal> N_CANTIDAD { get; set; }
        public Nullable<decimal> N_COSTO { get; set; }
        public Nullable<decimal> N_SUBTOTAL { get; set; }
        public string S_TIPO { get; set; }
        public Nullable<int> N_CODSICOF { get; set; }
        public string S_DESCRIPCION { get; set; }

        [ForeignKey("ID_FACTURA")]
        public virtual FACTURA FACTURA { get; set; }
    }
}
