//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.GestionDocumental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS
    {
        public int intIdTipo { get; set; }
        public string strNombre { get; set; }
        public string strConfiguracion { get; set; }
    }
}
