//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("QRYINSTALACIONDEC", Schema = "GENERAL")]
    public partial class QRYINSTALACIONDEC
    {
        [Key]
        public Nullable<int> ID_TERCERO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public Nullable<long> NRO_DOCUMENTO { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string CODIGO_CIIU_ORGANIZACION { get; set; }
        public string CIIU_ORGANIZACION { get; set; }
        public Nullable<int> TELEFONO_ORGANIZACION { get; set; }
        public string EMAIL_ORGANIZACION { get; set; }
        public string SIGLA { get; set; }
        public string REPRESENTANTE_LEGAL { get; set; }
        public string TIPO { get; set; }
        public int ID_INSTALACION { get; set; }
        public Nullable<System.DateTime> D_INICIO { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string CODIGO_TIPO_INSTALACION { get; set; }
        public string TIPO_INSTALACION { get; set; }
        public string CODIGO_CIIU_INSTALACION { get; set; }
        public string CIIU_INSTALACION { get; set; }
        public string MUNICIPIO { get; set; }
        public string DIRECCION { get; set; }
        public string DIRECCION_ESPECIAL { get; set; }
        public string NOMBRE_INSTALACION { get; set; }
        public string TELEFONO_INSTALACION { get; set; }
        public Nullable<decimal> CONTADOR { get; set; }
    }
}
