//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_APARCAMIENTOS
    {
        public int Id_Aparcamiento { get; set; }
        public string Descripcion { get; set; }
        public int Num_Puestos { get; set; }
        public string NombreCorto { get; set; }
        public int TEspera { get; set; }
        public int TAperturaManto { get; set; }
        public int TAperturaPrestamo { get; set; }
        public bool EsHabilitada { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
        public Nullable<int> Id_Poblacion { get; set; }
        public string id_team { get; set; }
        public string Compañia_3g { get; set; }
        public string Telefono { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string mail { get; set; }
        public Nullable<bool> oculta { get; set; }
        public Nullable<int> tiempo_cadencia { get; set; }
        public Nullable<bool> es_manual { get; set; }
        public string descripcion_web { get; set; }
        public Nullable<int> orden { get; set; }
        public string foto { get; set; }
        public Nullable<int> zona { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> cerrada { get; set; }
        public Nullable<int> es_cdo { get; set; }
        public Nullable<bool> Oculta_App { get; set; }
    }
}
