//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesEnCiclaSQL : DbContext
    {
        public EntitiesEnCiclaSQL()
            : base("name=EntitiesEnCiclaSQL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_APARCAMIENTOS> B_APARCAMIENTOS { get; set; }
        public virtual DbSet<P_BICICLETAS> P_BICICLETAS { get; set; }
        public virtual DbSet<P_OPERADORES> P_OPERADORES { get; set; }
        public virtual DbSet<P_USUARIOS> P_USUARIOS { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
        public virtual DbSet<I_HISTORICO_PRESTAMO> I_HISTORICO_PRESTAMO { get; set; }
    }
}
