//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_HISTORICO_PRESTAMO
    {
        public long Id_Historico_Prestamo { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public string Id_Tag_Bicicleta { get; set; }
        public Nullable<System.DateTime> Fecha_Prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_Devolucion { get; set; }
        public Nullable<int> Id_Aparcamiento_Origen { get; set; }
        public Nullable<int> Posicion_Origen { get; set; }
        public Nullable<int> Id_Aparcamiento_Destino { get; set; }
        public Nullable<int> Posicion_Destino { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string DescripcionImporte { get; set; }
        public string operario { get; set; }
        public string Num_Bici_Hist { get; set; }
    }
}
