//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_BICICLETAS
    {
        public string Id_Bicicleta_Tag { get; set; }
        public int Id_Estado { get; set; }
        public Nullable<int> Id_Tipo { get; set; }
        public Nullable<int> Num_bicicleta { get; set; }
        public Nullable<int> Id_Poblacion { get; set; }
        public string Cod_Barras { get; set; }
    }
}
