//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_OPERADORES
    {
        public string Login { get; set; }
        public string Passwd { get; set; }
        public string Per_Consulta { get; set; }
        public string Per_Modificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string DNI { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public string Poblacion { get; set; }
        public Nullable<int> Id_Provincia { get; set; }
        public string Telefono { get; set; }
    }
}
