//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_USUARIOS
    {
        public int Id_Usuario { get; set; }
        public Nullable<int> Id_Sitio_Registro { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string DNI { get; set; }
        public string Letra { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public string Telefono { get; set; }
        public string Numero_Tarjeta { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public string PIN { get; set; }
        public bool Es_Tutor { get; set; }
        public bool Es_Turista { get; set; }
        public bool Es_Residente { get; set; }
        public string Nombre_M { get; set; }
        public string Apellido1_M { get; set; }
        public string Apellido2_M { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<bool> Es_Mantenimiento { get; set; }
        public Nullable<int> Id_Perfil { get; set; }
        public Nullable<System.DateTime> Fecha_Caducidad { get; set; }
        public string TarjetaExterna { get; set; }
        public string LoginUsuario { get; set; }
        public string Clave { get; set; }
        public string email { get; set; }
        public Nullable<bool> PendienteOnLine { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> idTipoUso { get; set; }
        public Nullable<decimal> Monedero { get; set; }
        public Nullable<System.DateTime> FechaFinMonedero { get; set; }
        public Nullable<int> idDescuento { get; set; }
        public string TarjetaCredito { get; set; }
        public string MesCaducidad { get; set; }
        public string AnoCaducidad { get; set; }
        public Nullable<decimal> CosteAlta { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<int> idNacionalidad { get; set; }
        public string DNI_M { get; set; }
        public Nullable<int> IdTipoBonoSolicitado { get; set; }
        public string Sexo { get; set; }
        public string Sexo_M { get; set; }
        public string TelefonoMovil { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento_M { get; set; }
        public Nullable<bool> TarjetaEnOficina { get; set; }
        public Nullable<int> Id_Poblacion { get; set; }
        public Nullable<System.DateTime> Fecha_Caducidad_Seguro { get; set; }
        public string Codigo_Patrocinador { get; set; }
        public Nullable<decimal> Comision_Patrocinador { get; set; }
        public Nullable<bool> Contacto { get; set; }
        public Nullable<bool> desha_dni { get; set; }
        public string RH { get; set; }
        public string PerContacto { get; set; }
        public string TelContacto { get; set; }
        public Nullable<int> Estrato { get; set; }
        public string Ocupacion { get; set; }
        public string Institucion { get; set; }
        public string Departamento { get; set; }
        public string Consecutivo { get; set; }
        public string Empresa { get; set; }
        public string tel_fijo { get; set; }
        public Nullable<bool> metro { get; set; }
        public string TransporteRemplaza { get; set; }
    }
}
