//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Areas.EnCicla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zonas
    {
        public int id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    }
}
