/*! 
* DevExtreme Web
* Version: 14.2.6
* Build date: Mar 18, 2015
*
* Copyright (c) 2012 - 2015 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("es", {messages: {
        Yes: "Si",
        No: "No",
        Cancel: "Cancelar",
        Clear: "Limpiar",
        Done: "Hecho",
        Loading: "Cargando...",
        Select: "Seleccionar...",
        Search: "Buscar...",
        Back: "Atras",
        OK: "OK",
        "dxCollectionWidget-noDataText": "No se encontraron datos",
        "validation-required": "Requerido",
        "validation-required-formatted": "{0} es Requerido",
        "validation-numeric": "El valor debe ser un Numero",
        "validation-numeric-formatted": "{0} debe ser un Numero",
        "validation-range": "El valor esta por fuera del rango",
        "validation-range-formatted": "{0} esta por fuera del rango",
        "validation-stringLength": "La longitud del valor es incorrecta",
        "validation-stringLength-formatted": "La longitud de {0} es incorrecta",
        "validation-custom": "El valor es invalido",
        "validation-custom-formatted": "{0} es invalido",
        "validation-compare": "Los valores no coinciden",
        "validation-compare-formatted": "{0} no coincide",
        "validation-pattern": "Los valores no coinciden con el patron",
        "validation-pattern-formatted": "{0} no coincide con el patron",
        "validation-email": "Correo electronico invalido",
        "validation-email-formatted": "{0} es invalido"
    }});
Globalize.addCultureInfo("es", {messages: {
        "dxLookup-searchPlaceholder": "Numero caracter minimo: {0}",
        "dxList-pullingDownText": "Desplegar para refrescar...",
        "dxList-pulledDownText": "Liberar para refrescar...",
        "dxList-refreshingText": "Refrescando...",
        "dxList-pageLoadingText": "Cargando...",
        "dxList-nextButtonText": "Mas",
        "dxList-selectAll": "Seleccionar Todo",
        "dxListEditDecorator-delete": "Eliminar",
        "dxListEditDecorator-more": "Mas",
        "dxScrollView-pullingDownText": "Desplegar para refrescar...",
        "dxScrollView-pulledDownText": "Liberar para refrescar...",
        "dxScrollView-refreshingText": "Refrescando...",
        "dxScrollView-reachBottomText": "Cargando...",
        "dxDateBox-simulatedDataPickerTitleTime": "Seleccionar Hora",
        "dxDateBox-simulatedDataPickerTitleDate": "Seleccionar Fecha",
        "dxDateBox-simulatedDataPickerTitleDateTime": "Seleccionar Fecha y Hora",
        "dxFileUploader-selectFile": "Seleccionar Archivo",
        "dxFileUploader-dropFile": "o Soltar Archivo Aqui",
        "dxFileUploader-bytes": "Bytes",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb"
    }});
Globalize.addCultureInfo("es", {messages: {
        "dxDataGrid-columnChooserTitle": "Selector de Columna",
        "dxDataGrid-columnChooserEmptyText": "Arrastrar una columna aqui para ocultarla",
        "dxDataGrid-groupContinuesMessage": "Continúa en la página siguiente",
        "dxDataGrid-groupContinuedMessage": "Viene de la página anterior",
        "dxDataGrid-editingEditRow": "Editar",
        "dxDataGrid-editingSaveRowChanges": "Guardar",
        "dxDataGrid-editingCancelRowChanges": "Cancelar",
        "dxDataGrid-editingDeleteRow": "Eliminar",
        "dxDataGrid-editingUndeleteRow": "Recuperar",
        "dxDataGrid-editingConfirmDeleteMessage": "Esta seguro(a) que desea eliminar el registro?",
        "dxDataGrid-editingConfirmDeleteTitle": "",
        "dxDataGrid-groupPanelEmptyText": "Arrastrar un encabezado de columna aqui para agruparla",
        "dxDataGrid-noDataText": "Sin Datos",
        "dxDataGrid-searchPanelPlaceholder": "Buscar...",
        "dxDataGrid-filterRowShowAllText": "(Todos)",
        "dxDataGrid-filterRowResetOperationText": "Reiniciar",
        "dxDataGrid-filterRowOperationEquals": "Igual",
        "dxDataGrid-filterRowOperationNotEquals": "Diferente",
        "dxDataGrid-filterRowOperationLess": "Menor que",
        "dxDataGrid-filterRowOperationLessOrEquals": "Menor o Igual a",
        "dxDataGrid-filterRowOperationGreater": "Mayor que",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Mayor o Igual a",
        "dxDataGrid-filterRowOperationStartsWith": "Comienza con",
        "dxDataGrid-filterRowOperationContains": "Contiene",
        "dxDataGrid-filterRowOperationNotContains": "No Contiene",
        "dxDataGrid-filterRowOperationEndsWith": "Finaliza con",
        "dxDataGrid-applyFilterText": "Aplicar Filtro",
        "dxDataGrid-trueText": "verdadero",
        "dxDataGrid-falseText": "falso",
        "dxDataGrid-sortingAscendingText": "Orden Ascendente",
        "dxDataGrid-sortingDescendingText": "Orden Descendente",
        "dxDataGrid-sortingClearText": "Limpiar Orden",
        "dxDataGrid-editingSaveAllChanges": "Almacenar Cambios",
        "dxDataGrid-editingCancelAllChanges": "Cancelar Cambios",
        "dxDataGrid-editingAddRow": "Insertar Registro",
        "dxDataGrid-summaryMin": "Min: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Min de {1} es {0}",
        "dxDataGrid-summaryMax": "Max: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Max de {1} es {0}",
        "dxDataGrid-summaryAvg": "Prom: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Prom de {1} es {0}",
        "dxDataGrid-summarySum": "Suma: {0}",
        "dxDataGrid-summarySumOtherColumn": "Suma de {1} es {0}",
        "dxDataGrid-summaryCount": "Total: {0}",
        "dxPager-infoText": "Pagina {0} de {1}"
    }});
