//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("QRY_TRAMITEPRIORITARIO", Schema = "TRAMITES")]
    public partial class QRY_TRAMITEPRIORITARIO
    {
        public string PRIORITARIO { get; set; }
        [Key]
        public decimal CODTRAMITE { get; set; }
    }
}
