//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesFloraOracle : DbContext
    {
        public EntitiesFloraOracle()
            : base("name=EntitiesFloraOracle")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual int SP_ASOCIAR_DESASOCIAR_ARBOL(Nullable<decimal> iDTEMP, Nullable<decimal> iDARBOL)
        {
            var iDTEMPParameter = iDTEMP.HasValue ?
                new ObjectParameter("IDTEMP", iDTEMP) :
                new ObjectParameter("IDTEMP", typeof(decimal));
    
            var iDARBOLParameter = iDARBOL.HasValue ?
                new ObjectParameter("IDARBOL", iDARBOL) :
                new ObjectParameter("IDARBOL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ASOCIAR_DESASOCIAR_ARBOL", iDTEMPParameter, iDARBOLParameter);
        }
    
        public virtual int SP_ELIMINAR_DOC_TALA(Nullable<decimal> aRRIDARBOL)
        {
            var aRRIDARBOLParameter = aRRIDARBOL.HasValue ?
                new ObjectParameter("ARRIDARBOL", aRRIDARBOL) :
                new ObjectParameter("ARRIDARBOL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_DOC_TALA", aRRIDARBOLParameter);
        }
    
        public virtual int SP_ELIMINAR_DOC_TALA_TODO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_DOC_TALA_TODO");
        }
    
        public virtual int SP_ELIMINAR_FOTO_TALA(Nullable<decimal> iD_FOTO)
        {
            var iD_FOTOParameter = iD_FOTO.HasValue ?
                new ObjectParameter("ID_FOTO", iD_FOTO) :
                new ObjectParameter("ID_FOTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_FOTO_TALA", iD_FOTOParameter);
        }
    
        public virtual int SP_GET_ACTULIZAR_DOMINIOS_APPT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ACTULIZAR_DOMINIOS_APPT");
        }
    
        public virtual int SP_GET_AGENTE_DM(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_AGENTE_DM", jSONOUT);
        }
    
        public virtual int SP_GET_ARBOLES(Nullable<decimal> iDVISITA, string lSTIDIND, ObjectParameter jSONOUT)
        {
            var iDVISITAParameter = iDVISITA.HasValue ?
                new ObjectParameter("IDVISITA", iDVISITA) :
                new ObjectParameter("IDVISITA", typeof(decimal));
    
            var lSTIDINDParameter = lSTIDIND != null ?
                new ObjectParameter("LSTIDIND", lSTIDIND) :
                new ObjectParameter("LSTIDIND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ARBOLES", iDVISITAParameter, lSTIDINDParameter, jSONOUT);
        }
    
        public virtual int SP_GET_ARBOLES_CARGA(Nullable<decimal> iD_TRAMITE, Nullable<decimal> iD_CONTRATO, ObjectParameter jSONOUT)
        {
            var iD_TRAMITEParameter = iD_TRAMITE.HasValue ?
                new ObjectParameter("ID_TRAMITE", iD_TRAMITE) :
                new ObjectParameter("ID_TRAMITE", typeof(decimal));
    
            var iD_CONTRATOParameter = iD_CONTRATO.HasValue ?
                new ObjectParameter("ID_CONTRATO", iD_CONTRATO) :
                new ObjectParameter("ID_CONTRATO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ARBOLES_CARGA", iD_TRAMITEParameter, iD_CONTRATOParameter, jSONOUT);
        }
    
        public virtual int SP_GET_COMBOHIJO(Nullable<decimal> iDPRE, ObjectParameter jSONOUT)
        {
            var iDPREParameter = iDPRE.HasValue ?
                new ObjectParameter("IDPRE", iDPRE) :
                new ObjectParameter("IDPRE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_COMBOHIJO", iDPREParameter, jSONOUT);
        }
    
        public virtual int SP_GET_DATOSF(string sTR_SQL, ObjectParameter jSONOUT)
        {
            var sTR_SQLParameter = sTR_SQL != null ?
                new ObjectParameter("STR_SQL", sTR_SQL) :
                new ObjectParameter("STR_SQL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_DATOSF", sTR_SQLParameter, jSONOUT);
        }
    
        public virtual int SP_GET_ENCUESTAS(Nullable<decimal> iDESTADO, Nullable<decimal> iD_FORM, Nullable<decimal> iDVIGENCIA, ObjectParameter jSONOUT)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            var iD_FORMParameter = iD_FORM.HasValue ?
                new ObjectParameter("ID_FORM", iD_FORM) :
                new ObjectParameter("ID_FORM", typeof(decimal));
    
            var iDVIGENCIAParameter = iDVIGENCIA.HasValue ?
                new ObjectParameter("IDVIGENCIA", iDVIGENCIA) :
                new ObjectParameter("IDVIGENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ENCUESTAS", iDESTADOParameter, iD_FORMParameter, iDVIGENCIAParameter, jSONOUT);
        }
    
        public virtual int SP_GET_ENCUESTAS_REPORT(Nullable<decimal> iDESTADO, ObjectParameter jSONOUT)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ENCUESTAS_REPORT", iDESTADOParameter, jSONOUT);
        }
    
        public virtual int SP_GET_ENTORNO(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ENTORNO", jSONOUT);
        }
    
        public virtual int SP_GET_ESPECIES(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ESPECIES", jSONOUT);
        }
    
        public virtual int SP_GET_ESTADOS(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ESTADOS", jSONOUT);
        }
    
        public virtual int SP_GET_INTV_VISITA_TEMP(Nullable<decimal> iDVISITA, ObjectParameter jSONOUT)
        {
            var iDVISITAParameter = iDVISITA.HasValue ?
                new ObjectParameter("IDVISITA", iDVISITA) :
                new ObjectParameter("IDVISITA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_INTV_VISITA_TEMP", iDVISITAParameter, jSONOUT);
        }
    
        public virtual int SP_GET_RIESGO(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_RIESGO", jSONOUT);
        }
    
        public virtual int SP_GET_SINTOMA_DM(ObjectParameter jSONOUT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_SINTOMA_DM", jSONOUT);
        }
    
        public virtual int SP_SET_ARBOLES(Nullable<decimal> iDVISITA, string jSONOUT, ObjectParameter rTA)
        {
            var iDVISITAParameter = iDVISITA.HasValue ?
                new ObjectParameter("IDVISITA", iDVISITA) :
                new ObjectParameter("IDVISITA", typeof(decimal));
    
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ARBOLES", iDVISITAParameter, jSONOUTParameter, rTA);
        }
    
        public virtual int SP_SET_ARBOLES_CARGA(string jSONOUT, Nullable<decimal> fIN, ObjectParameter rTA)
        {
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            var fINParameter = fIN.HasValue ?
                new ObjectParameter("FIN", fIN) :
                new ObjectParameter("FIN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ARBOLES_CARGA", jSONOUTParameter, fINParameter, rTA);
        }
    
        public virtual int SP_SET_ARBOLES_CARGA_CONTRATO(string jSONOUT, Nullable<decimal> fIN, ObjectParameter rTA)
        {
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            var fINParameter = fIN.HasValue ?
                new ObjectParameter("FIN", fIN) :
                new ObjectParameter("FIN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ARBOLES_CARGA_CONTRATO", jSONOUTParameter, fINParameter, rTA);
        }
    
        public virtual int SP_SET_CLONAR_ENCUESTA_EXTERNO(Nullable<decimal> iDVIG, string vALOR, Nullable<decimal> cOD_FUN, Nullable<decimal> iDES, Nullable<decimal> iNSTALACION)
        {
            var iDVIGParameter = iDVIG.HasValue ?
                new ObjectParameter("IDVIG", iDVIG) :
                new ObjectParameter("IDVIG", typeof(decimal));
    
            var vALORParameter = vALOR != null ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(string));
    
            var cOD_FUNParameter = cOD_FUN.HasValue ?
                new ObjectParameter("COD_FUN", cOD_FUN) :
                new ObjectParameter("COD_FUN", typeof(decimal));
    
            var iDESParameter = iDES.HasValue ?
                new ObjectParameter("IDES", iDES) :
                new ObjectParameter("IDES", typeof(decimal));
    
            var iNSTALACIONParameter = iNSTALACION.HasValue ?
                new ObjectParameter("INSTALACION", iNSTALACION) :
                new ObjectParameter("INSTALACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_CLONAR_ENCUESTA_EXTERNO", iDVIGParameter, vALORParameter, cOD_FUNParameter, iDESParameter, iNSTALACIONParameter);
        }
    
        public virtual int SP_SET_CREAR_ESTADO_GENERICO(Nullable<decimal> iDENC, Nullable<decimal> cOD_FUN, ObjectParameter rTA, Nullable<decimal> iDTERCERO, Nullable<decimal> iDINSTALACION, Nullable<decimal> tIPORAD)
        {
            var iDENCParameter = iDENC.HasValue ?
                new ObjectParameter("IDENC", iDENC) :
                new ObjectParameter("IDENC", typeof(decimal));
    
            var cOD_FUNParameter = cOD_FUN.HasValue ?
                new ObjectParameter("COD_FUN", cOD_FUN) :
                new ObjectParameter("COD_FUN", typeof(decimal));
    
            var iDTERCEROParameter = iDTERCERO.HasValue ?
                new ObjectParameter("IDTERCERO", iDTERCERO) :
                new ObjectParameter("IDTERCERO", typeof(decimal));
    
            var iDINSTALACIONParameter = iDINSTALACION.HasValue ?
                new ObjectParameter("IDINSTALACION", iDINSTALACION) :
                new ObjectParameter("IDINSTALACION", typeof(decimal));
    
            var tIPORADParameter = tIPORAD.HasValue ?
                new ObjectParameter("TIPORAD", tIPORAD) :
                new ObjectParameter("TIPORAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_CREAR_ESTADO_GENERICO", iDENCParameter, cOD_FUNParameter, rTA, iDTERCEROParameter, iDINSTALACIONParameter, tIPORADParameter);
        }
    
        public virtual int SP_SET_DOC_TALA(Nullable<decimal> iDARBOL, byte[] dOC, Nullable<decimal> tIPO)
        {
            var iDARBOLParameter = iDARBOL.HasValue ?
                new ObjectParameter("IDARBOL", iDARBOL) :
                new ObjectParameter("IDARBOL", typeof(decimal));
    
            var dOCParameter = dOC != null ?
                new ObjectParameter("DOC", dOC) :
                new ObjectParameter("DOC", typeof(byte[]));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_DOC_TALA", iDARBOLParameter, dOCParameter, tIPOParameter);
        }
    
        public virtual int SP_SET_ELI_ENC_CARDINALIAD(Nullable<decimal> vAL, Nullable<decimal> iNST)
        {
            var vALParameter = vAL.HasValue ?
                new ObjectParameter("VAL", vAL) :
                new ObjectParameter("VAL", typeof(decimal));
    
            var iNSTParameter = iNST.HasValue ?
                new ObjectParameter("INST", iNST) :
                new ObjectParameter("INST", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ELI_ENC_CARDINALIAD", vALParameter, iNSTParameter);
        }
    
        public virtual int SP_SET_ELIMINAR_ENCUESTA(Nullable<decimal> iDESTADO)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ELIMINAR_ENCUESTA", iDESTADOParameter);
        }
    
        public virtual int SP_SET_ENCUESTA_ROL2(Nullable<decimal> iDVIGENCIA, string nOMBREENCU, string fECHAINI, Nullable<decimal> iDENCUENTA, string fECHAFIN, string aRRENCUESTA, Nullable<decimal> rOL, string tERMINOS, Nullable<decimal> tIPOINSTALACION, Nullable<decimal> cARD, Nullable<decimal> rADICAR, string nOMBREITEM)
        {
            var iDVIGENCIAParameter = iDVIGENCIA.HasValue ?
                new ObjectParameter("IDVIGENCIA", iDVIGENCIA) :
                new ObjectParameter("IDVIGENCIA", typeof(decimal));
    
            var nOMBREENCUParameter = nOMBREENCU != null ?
                new ObjectParameter("NOMBREENCU", nOMBREENCU) :
                new ObjectParameter("NOMBREENCU", typeof(string));
    
            var fECHAINIParameter = fECHAINI != null ?
                new ObjectParameter("FECHAINI", fECHAINI) :
                new ObjectParameter("FECHAINI", typeof(string));
    
            var iDENCUENTAParameter = iDENCUENTA.HasValue ?
                new ObjectParameter("IDENCUENTA", iDENCUENTA) :
                new ObjectParameter("IDENCUENTA", typeof(decimal));
    
            var fECHAFINParameter = fECHAFIN != null ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(string));
    
            var aRRENCUESTAParameter = aRRENCUESTA != null ?
                new ObjectParameter("ARRENCUESTA", aRRENCUESTA) :
                new ObjectParameter("ARRENCUESTA", typeof(string));
    
            var rOLParameter = rOL.HasValue ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(decimal));
    
            var tERMINOSParameter = tERMINOS != null ?
                new ObjectParameter("TERMINOS", tERMINOS) :
                new ObjectParameter("TERMINOS", typeof(string));
    
            var tIPOINSTALACIONParameter = tIPOINSTALACION.HasValue ?
                new ObjectParameter("TIPOINSTALACION", tIPOINSTALACION) :
                new ObjectParameter("TIPOINSTALACION", typeof(decimal));
    
            var cARDParameter = cARD.HasValue ?
                new ObjectParameter("CARD", cARD) :
                new ObjectParameter("CARD", typeof(decimal));
    
            var rADICARParameter = rADICAR.HasValue ?
                new ObjectParameter("RADICAR", rADICAR) :
                new ObjectParameter("RADICAR", typeof(decimal));
    
            var nOMBREITEMParameter = nOMBREITEM != null ?
                new ObjectParameter("NOMBREITEM", nOMBREITEM) :
                new ObjectParameter("NOMBREITEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ENCUESTA_ROL2", iDVIGENCIAParameter, nOMBREENCUParameter, fECHAINIParameter, iDENCUENTAParameter, fECHAFINParameter, aRRENCUESTAParameter, rOLParameter, tERMINOSParameter, tIPOINSTALACIONParameter, cARDParameter, rADICARParameter, nOMBREITEMParameter);
        }
    
        public virtual int SP_SET_ESTADO_CARDINALIDAD(Nullable<decimal> iDENC, Nullable<decimal> cOD_FUN, Nullable<decimal> iDTERCERO, Nullable<decimal> iDINSTALACION, Nullable<decimal> cARD, Nullable<decimal> iDVIGENCIA, string vIGEN)
        {
            var iDENCParameter = iDENC.HasValue ?
                new ObjectParameter("IDENC", iDENC) :
                new ObjectParameter("IDENC", typeof(decimal));
    
            var cOD_FUNParameter = cOD_FUN.HasValue ?
                new ObjectParameter("COD_FUN", cOD_FUN) :
                new ObjectParameter("COD_FUN", typeof(decimal));
    
            var iDTERCEROParameter = iDTERCERO.HasValue ?
                new ObjectParameter("IDTERCERO", iDTERCERO) :
                new ObjectParameter("IDTERCERO", typeof(decimal));
    
            var iDINSTALACIONParameter = iDINSTALACION.HasValue ?
                new ObjectParameter("IDINSTALACION", iDINSTALACION) :
                new ObjectParameter("IDINSTALACION", typeof(decimal));
    
            var cARDParameter = cARD.HasValue ?
                new ObjectParameter("CARD", cARD) :
                new ObjectParameter("CARD", typeof(decimal));
    
            var iDVIGENCIAParameter = iDVIGENCIA.HasValue ?
                new ObjectParameter("IDVIGENCIA", iDVIGENCIA) :
                new ObjectParameter("IDVIGENCIA", typeof(decimal));
    
            var vIGENParameter = vIGEN != null ?
                new ObjectParameter("VIGEN", vIGEN) :
                new ObjectParameter("VIGEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ESTADO_CARDINALIDAD", iDENCParameter, cOD_FUNParameter, iDTERCEROParameter, iDINSTALACIONParameter, cARDParameter, iDVIGENCIAParameter, vIGENParameter);
        }
    
        public virtual int SP_SET_FOTO_INTV(Nullable<decimal> iDTERCERO, string oBS, string jSONOUT)
        {
            var iDTERCEROParameter = iDTERCERO.HasValue ?
                new ObjectParameter("IDTERCERO", iDTERCERO) :
                new ObjectParameter("IDTERCERO", typeof(decimal));
    
            var oBSParameter = oBS != null ?
                new ObjectParameter("OBS", oBS) :
                new ObjectParameter("OBS", typeof(string));
    
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_FOTO_INTV", iDTERCEROParameter, oBSParameter, jSONOUTParameter);
        }
    
        public virtual int SP_SET_FOTO_TALA(Nullable<decimal> iDTEMP, byte[] fOTO)
        {
            var iDTEMPParameter = iDTEMP.HasValue ?
                new ObjectParameter("IDTEMP", iDTEMP) :
                new ObjectParameter("IDTEMP", typeof(decimal));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_FOTO_TALA", iDTEMPParameter, fOTOParameter);
        }
    
        public virtual int SP_SET_GUARDARRADICADO(Nullable<decimal> iDESTADO, string cORADICADO)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            var cORADICADOParameter = cORADICADO != null ?
                new ObjectParameter("CORADICADO", cORADICADO) :
                new ObjectParameter("CORADICADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_GUARDARRADICADO", iDESTADOParameter, cORADICADOParameter);
        }
    
        public virtual int SP_SET_INDICE_COR(Nullable<decimal> iDDOC, string fECHARADICADO, string rADICADO, Nullable<decimal> iDTRAMITE, string aSUNTO, string nOMBREUSUARIO, string nOMBRETERCERO, Nullable<decimal> iDTERCERO, Nullable<decimal> iDINSTALACION, ObjectParameter rTA)
        {
            var iDDOCParameter = iDDOC.HasValue ?
                new ObjectParameter("IDDOC", iDDOC) :
                new ObjectParameter("IDDOC", typeof(decimal));
    
            var fECHARADICADOParameter = fECHARADICADO != null ?
                new ObjectParameter("FECHARADICADO", fECHARADICADO) :
                new ObjectParameter("FECHARADICADO", typeof(string));
    
            var rADICADOParameter = rADICADO != null ?
                new ObjectParameter("RADICADO", rADICADO) :
                new ObjectParameter("RADICADO", typeof(string));
    
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            var aSUNTOParameter = aSUNTO != null ?
                new ObjectParameter("ASUNTO", aSUNTO) :
                new ObjectParameter("ASUNTO", typeof(string));
    
            var nOMBREUSUARIOParameter = nOMBREUSUARIO != null ?
                new ObjectParameter("NOMBREUSUARIO", nOMBREUSUARIO) :
                new ObjectParameter("NOMBREUSUARIO", typeof(string));
    
            var nOMBRETERCEROParameter = nOMBRETERCERO != null ?
                new ObjectParameter("NOMBRETERCERO", nOMBRETERCERO) :
                new ObjectParameter("NOMBRETERCERO", typeof(string));
    
            var iDTERCEROParameter = iDTERCERO.HasValue ?
                new ObjectParameter("IDTERCERO", iDTERCERO) :
                new ObjectParameter("IDTERCERO", typeof(decimal));
    
            var iDINSTALACIONParameter = iDINSTALACION.HasValue ?
                new ObjectParameter("IDINSTALACION", iDINSTALACION) :
                new ObjectParameter("IDINSTALACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_INDICE_COR", iDDOCParameter, fECHARADICADOParameter, rADICADOParameter, iDTRAMITEParameter, aSUNTOParameter, nOMBREUSUARIOParameter, nOMBRETERCEROParameter, iDTERCEROParameter, iDINSTALACIONParameter, rTA);
        }
    
        public virtual int SP_SET_INDICE_TALA(Nullable<decimal> iDDOC, string mEDIORES, string mAIL, string tIPOUSER, string tIPOSOLI, string rEMITENTE, Nullable<decimal> iDTRAMITE, string mUNICIPIOARBOL, string dIRECCIONMUNICIPIO, string fECHARADICADO, string rADICADO, ObjectParameter rTA)
        {
            var iDDOCParameter = iDDOC.HasValue ?
                new ObjectParameter("IDDOC", iDDOC) :
                new ObjectParameter("IDDOC", typeof(decimal));
    
            var mEDIORESParameter = mEDIORES != null ?
                new ObjectParameter("MEDIORES", mEDIORES) :
                new ObjectParameter("MEDIORES", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var tIPOUSERParameter = tIPOUSER != null ?
                new ObjectParameter("TIPOUSER", tIPOUSER) :
                new ObjectParameter("TIPOUSER", typeof(string));
    
            var tIPOSOLIParameter = tIPOSOLI != null ?
                new ObjectParameter("TIPOSOLI", tIPOSOLI) :
                new ObjectParameter("TIPOSOLI", typeof(string));
    
            var rEMITENTEParameter = rEMITENTE != null ?
                new ObjectParameter("REMITENTE", rEMITENTE) :
                new ObjectParameter("REMITENTE", typeof(string));
    
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            var mUNICIPIOARBOLParameter = mUNICIPIOARBOL != null ?
                new ObjectParameter("MUNICIPIOARBOL", mUNICIPIOARBOL) :
                new ObjectParameter("MUNICIPIOARBOL", typeof(string));
    
            var dIRECCIONMUNICIPIOParameter = dIRECCIONMUNICIPIO != null ?
                new ObjectParameter("DIRECCIONMUNICIPIO", dIRECCIONMUNICIPIO) :
                new ObjectParameter("DIRECCIONMUNICIPIO", typeof(string));
    
            var fECHARADICADOParameter = fECHARADICADO != null ?
                new ObjectParameter("FECHARADICADO", fECHARADICADO) :
                new ObjectParameter("FECHARADICADO", typeof(string));
    
            var rADICADOParameter = rADICADO != null ?
                new ObjectParameter("RADICADO", rADICADO) :
                new ObjectParameter("RADICADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_INDICE_TALA", iDDOCParameter, mEDIORESParameter, mAILParameter, tIPOUSERParameter, tIPOSOLIParameter, rEMITENTEParameter, iDTRAMITEParameter, mUNICIPIOARBOLParameter, dIRECCIONMUNICIPIOParameter, fECHARADICADOParameter, rADICADOParameter, rTA);
        }
    
        public virtual int SP_SET_INDICE_TALACOD(Nullable<decimal> iDDOC, string fECHARADICADO, string rADICADO, string nOMBRE, Nullable<decimal> iDTRAMITE, string mUNICIPIOARBOL, string dIRECCIONMUNICIPIO, ObjectParameter rTA)
        {
            var iDDOCParameter = iDDOC.HasValue ?
                new ObjectParameter("IDDOC", iDDOC) :
                new ObjectParameter("IDDOC", typeof(decimal));
    
            var fECHARADICADOParameter = fECHARADICADO != null ?
                new ObjectParameter("FECHARADICADO", fECHARADICADO) :
                new ObjectParameter("FECHARADICADO", typeof(string));
    
            var rADICADOParameter = rADICADO != null ?
                new ObjectParameter("RADICADO", rADICADO) :
                new ObjectParameter("RADICADO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            var mUNICIPIOARBOLParameter = mUNICIPIOARBOL != null ?
                new ObjectParameter("MUNICIPIOARBOL", mUNICIPIOARBOL) :
                new ObjectParameter("MUNICIPIOARBOL", typeof(string));
    
            var dIRECCIONMUNICIPIOParameter = dIRECCIONMUNICIPIO != null ?
                new ObjectParameter("DIRECCIONMUNICIPIO", dIRECCIONMUNICIPIO) :
                new ObjectParameter("DIRECCIONMUNICIPIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_INDICE_TALACOD", iDDOCParameter, fECHARADICADOParameter, rADICADOParameter, nOMBREParameter, iDTRAMITEParameter, mUNICIPIOARBOLParameter, dIRECCIONMUNICIPIOParameter, rTA);
        }
    
        public virtual int SP_SET_INTV_VISITA_TEMP(string jSONOUT, ObjectParameter rTA)
        {
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_INTV_VISITA_TEMP", jSONOUTParameter, rTA);
        }
    
        public virtual int SP_SET_MODIFICARENCUESTACARD(string jSONOUT)
        {
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_MODIFICARENCUESTACARD", jSONOUTParameter);
        }
    
        public virtual int SP_SET_MODIFICAR_ESTADO(Nullable<decimal> iDESTADO)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_MODIFICAR_ESTADO", iDESTADOParameter);
        }
    
        public virtual int SP_SET_MODIFICARVIGENCIA(Nullable<decimal> iDVIGENCIA, string vIGEN, Nullable<decimal> iDESTADO)
        {
            var iDVIGENCIAParameter = iDVIGENCIA.HasValue ?
                new ObjectParameter("IDVIGENCIA", iDVIGENCIA) :
                new ObjectParameter("IDVIGENCIA", typeof(decimal));
    
            var vIGENParameter = vIGEN != null ?
                new ObjectParameter("VIGEN", vIGEN) :
                new ObjectParameter("VIGEN", typeof(string));
    
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_MODIFICARVIGENCIA", iDVIGENCIAParameter, vIGENParameter, iDESTADOParameter);
        }
    
        public virtual int SP_SET_TALA_PODA(string jSONOUT, Nullable<decimal> iDTRAMITE, Nullable<decimal> cODFUNCIONARIO, ObjectParameter rTA)
        {
            var jSONOUTParameter = jSONOUT != null ?
                new ObjectParameter("JSONOUT", jSONOUT) :
                new ObjectParameter("JSONOUT", typeof(string));
    
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_TALA_PODA", jSONOUTParameter, iDTRAMITEParameter, cODFUNCIONARIOParameter, rTA);
        }
    
        public virtual int SP_SET_TERMINOSCONDICIONES(Nullable<decimal> iDTRAMITE, string mENSAJE, ObjectParameter rTA)
        {
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            var mENSAJEParameter = mENSAJE != null ?
                new ObjectParameter("MENSAJE", mENSAJE) :
                new ObjectParameter("MENSAJE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_TERMINOSCONDICIONES", iDTRAMITEParameter, mENSAJEParameter, rTA);
        }
    
        public virtual int SP_SET_TRAMITE_PMES(string mENSAJ, string fUNCIONARIO, string tAREA, string pREOCESO, ObjectParameter rTA, ObjectParameter rTA2, ObjectParameter rTA3, ObjectParameter rTA4)
        {
            var mENSAJParameter = mENSAJ != null ?
                new ObjectParameter("MENSAJ", mENSAJ) :
                new ObjectParameter("MENSAJ", typeof(string));
    
            var fUNCIONARIOParameter = fUNCIONARIO != null ?
                new ObjectParameter("FUNCIONARIO", fUNCIONARIO) :
                new ObjectParameter("FUNCIONARIO", typeof(string));
    
            var tAREAParameter = tAREA != null ?
                new ObjectParameter("TAREA", tAREA) :
                new ObjectParameter("TAREA", typeof(string));
    
            var pREOCESOParameter = pREOCESO != null ?
                new ObjectParameter("PREOCESO", pREOCESO) :
                new ObjectParameter("PREOCESO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_TRAMITE_PMES", mENSAJParameter, fUNCIONARIOParameter, tAREAParameter, pREOCESOParameter, rTA, rTA2, rTA3, rTA4);
        }
    
        public virtual int SP_SET_TRAMITE_TALA_PODA(string mENSAJ, ObjectParameter rTA, ObjectParameter rTA2, ObjectParameter rTA3, ObjectParameter rTA4)
        {
            var mENSAJParameter = mENSAJ != null ?
                new ObjectParameter("MENSAJ", mENSAJ) :
                new ObjectParameter("MENSAJ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_TRAMITE_TALA_PODA", mENSAJParameter, rTA, rTA2, rTA3, rTA4);
        }
    
        public virtual int SP_SET_URLRADICADO(Nullable<decimal> iDESTADO, string uRLRAD)
        {
            var iDESTADOParameter = iDESTADO.HasValue ?
                new ObjectParameter("IDESTADO", iDESTADO) :
                new ObjectParameter("IDESTADO", typeof(decimal));
    
            var uRLRADParameter = uRLRAD != null ?
                new ObjectParameter("URLRAD", uRLRAD) :
                new ObjectParameter("URLRAD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_URLRADICADO", iDESTADOParameter, uRLRADParameter);
        }
    
        public virtual int SP_SET_USO_URBANO(Nullable<decimal> iD_USOS, string cX, string cY, string dIR, Nullable<decimal> mUNICIPIO, string uBIC)
        {
            var iD_USOSParameter = iD_USOS.HasValue ?
                new ObjectParameter("ID_USOS", iD_USOS) :
                new ObjectParameter("ID_USOS", typeof(decimal));
    
            var cXParameter = cX != null ?
                new ObjectParameter("CX", cX) :
                new ObjectParameter("CX", typeof(string));
    
            var cYParameter = cY != null ?
                new ObjectParameter("CY", cY) :
                new ObjectParameter("CY", typeof(string));
    
            var dIRParameter = dIR != null ?
                new ObjectParameter("DIR", dIR) :
                new ObjectParameter("DIR", typeof(string));
    
            var mUNICIPIOParameter = mUNICIPIO.HasValue ?
                new ObjectParameter("MUNICIPIO", mUNICIPIO) :
                new ObjectParameter("MUNICIPIO", typeof(decimal));
    
            var uBICParameter = uBIC != null ?
                new ObjectParameter("UBIC", uBIC) :
                new ObjectParameter("UBIC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_USO_URBANO", iD_USOSParameter, cXParameter, cYParameter, dIRParameter, mUNICIPIOParameter, uBICParameter);
        }
    }
}
