//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesTramitesOracle : DbContext
    {
        public EntitiesTramitesOracle()
            : base("name=EntitiesTramitesOracle")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual int SP_ASIGNAR_TEMPORAL_TRAMITE(Nullable<decimal> cODTRAMITE, Nullable<decimal> cODTAREA, Nullable<decimal> cODFUNCIONARIO, Nullable<decimal> oRDEN, Nullable<decimal> vERSIONDOC, string dESCRIPCION, string rUTA, ObjectParameter rTARESULTADO)
        {
            var cODTRAMITEParameter = cODTRAMITE.HasValue ?
                new ObjectParameter("CODTRAMITE", cODTRAMITE) :
                new ObjectParameter("CODTRAMITE", typeof(decimal));
    
            var cODTAREAParameter = cODTAREA.HasValue ?
                new ObjectParameter("CODTAREA", cODTAREA) :
                new ObjectParameter("CODTAREA", typeof(decimal));
    
            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));
    
            var oRDENParameter = oRDEN.HasValue ?
                new ObjectParameter("ORDEN", oRDEN) :
                new ObjectParameter("ORDEN", typeof(decimal));
    
            var vERSIONDOCParameter = vERSIONDOC.HasValue ?
                new ObjectParameter("VERSIONDOC", vERSIONDOC) :
                new ObjectParameter("VERSIONDOC", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rUTAParameter = rUTA != null ?
                new ObjectParameter("RUTA", rUTA) :
                new ObjectParameter("RUTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ASIGNAR_TEMPORAL_TRAMITE", cODTRAMITEParameter, cODTAREAParameter, cODFUNCIONARIOParameter, oRDENParameter, vERSIONDOCParameter, dESCRIPCIONParameter, rUTAParameter, rTARESULTADO);
        }

        public virtual int SP_CREAR_INDICE_FULLTEXT(Nullable<decimal> cODTRAMITE, Nullable<decimal> cODDOCUMENTO, ObjectParameter rTARESULTADO)
        {
            var cODTRAMITEParameter = cODTRAMITE.HasValue ?
                new ObjectParameter("CODTRAMITE", cODTRAMITE) :
                new ObjectParameter("CODTRAMITE", typeof(decimal));

            var cODDOCUMENTOParameter = cODDOCUMENTO.HasValue ?
                new ObjectParameter("CODDOCUMENTO", cODDOCUMENTO) :
                new ObjectParameter("CODDOCUMENTO", typeof(decimal));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREAR_INDICE_FULLTEXT", cODTRAMITEParameter, cODDOCUMENTOParameter, rTARESULTADO);
        }

        public virtual int SP_AVANZA_TAREA(Nullable<decimal> tIPO, Nullable<decimal> cODTRAMITE, Nullable<decimal> cODTAREA, Nullable<decimal> cODTAREA_SIGUIENTE, Nullable<decimal> cODFUNCIONARIO, string cOPIAS, string cOMENTARIO, ObjectParameter rTARESULTADO)
        {
            return SP_AVANZA_TAREA(tIPO, cODTRAMITE, cODTAREA, cODTAREA_SIGUIENTE, cODFUNCIONARIO, null, cOPIAS, cOMENTARIO, rTARESULTADO);
        }

        public virtual int SP_AVANZA_TAREA(Nullable<decimal> tIPO, Nullable<decimal> cODTRAMITE, Nullable<decimal> cODTAREA, Nullable<decimal> cODTAREA_SIGUIENTE, Nullable<decimal> cODFUNCIONARIO, Nullable<decimal> cODFUNCIONARIOACTUAL, string cOPIAS, string cOMENTARIO, ObjectParameter rTARESULTADO)
        {
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(decimal));

            var cODTRAMITEParameter = cODTRAMITE.HasValue ?
                new ObjectParameter("CODTRAMITE", cODTRAMITE) :
                new ObjectParameter("CODTRAMITE", typeof(decimal));

            var cODTAREAParameter = cODTAREA.HasValue ?
                new ObjectParameter("CODTAREA", cODTAREA) :
                new ObjectParameter("CODTAREA", typeof(decimal));

            var cODTAREA_SIGUIENTEParameter = cODTAREA_SIGUIENTE.HasValue ?
                new ObjectParameter("CODTAREA_SIGUIENTE", cODTAREA_SIGUIENTE) :
                new ObjectParameter("CODTAREA_SIGUIENTE", typeof(decimal));

            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));

            var cODFUNCIONARIOACTUALParameter = cODFUNCIONARIOACTUAL.HasValue ?
                new ObjectParameter("CODFUNCIONARIOACTUAL", cODFUNCIONARIOACTUAL) :
                new ObjectParameter("CODFUNCIONARIOACTUAL", typeof(decimal));

            var cOPIASParameter = cOPIAS != null ?
                new ObjectParameter("COPIAS", cOPIAS) :
                new ObjectParameter("COPIAS", typeof(string));

            var cOMENTARIOParameter = cOMENTARIO != null ?
                new ObjectParameter("COMENTARIO", cOMENTARIO) :
                new ObjectParameter("COMENTARIO", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AVANZA_TAREA", tIPOParameter, cODTRAMITEParameter, cODTAREAParameter, cODTAREA_SIGUIENTEParameter, cODFUNCIONARIOParameter, cODFUNCIONARIOACTUALParameter, cOPIASParameter, cOMENTARIOParameter, rTARESULTADO);
        }

        public virtual int SP_AVANZA_TAREA_FORMULARIO(Nullable<decimal> cODTRAMITE, Nullable<decimal> cODTAREA, Nullable<decimal> cODTAREA_SIGUIENTE, Nullable<decimal> cODFUNCIONARIO, string fORMULARIO_SIGUIENTE, string cOPIAS, string cOMENTARIO, ObjectParameter rTARESULTADO)
        {
            var cODTRAMITEParameter = cODTRAMITE.HasValue ?
                new ObjectParameter("CODTRAMITE", cODTRAMITE) :
                new ObjectParameter("CODTRAMITE", typeof(decimal));
    
            var cODTAREAParameter = cODTAREA.HasValue ?
                new ObjectParameter("CODTAREA", cODTAREA) :
                new ObjectParameter("CODTAREA", typeof(decimal));
    
            var cODTAREA_SIGUIENTEParameter = cODTAREA_SIGUIENTE.HasValue ?
                new ObjectParameter("CODTAREA_SIGUIENTE", cODTAREA_SIGUIENTE) :
                new ObjectParameter("CODTAREA_SIGUIENTE", typeof(decimal));
    
            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));
    
            var fORMULARIO_SIGUIENTEParameter = fORMULARIO_SIGUIENTE != null ?
                new ObjectParameter("FORMULARIO_SIGUIENTE", fORMULARIO_SIGUIENTE) :
                new ObjectParameter("FORMULARIO_SIGUIENTE", typeof(string));
    
            var cOPIASParameter = cOPIAS != null ?
                new ObjectParameter("COPIAS", cOPIAS) :
                new ObjectParameter("COPIAS", typeof(string));
    
            var cOMENTARIOParameter = cOMENTARIO != null ?
                new ObjectParameter("COMENTARIO", cOMENTARIO) :
                new ObjectParameter("COMENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AVANZA_TAREA_FORMULARIO", cODTRAMITEParameter, cODTAREAParameter, cODTAREA_SIGUIENTEParameter, cODFUNCIONARIOParameter, fORMULARIO_SIGUIENTEParameter, cOPIASParameter, cOMENTARIOParameter, rTARESULTADO);
        }
    
        public virtual int SP_NUEVO_TRAMITE(Nullable<decimal> cODPROCESO, Nullable<decimal> cODTAREA, Nullable<decimal> cODFUNCIONARIO, string mENSAJE, ObjectParameter rESPCODTRAMITE, ObjectParameter rESPCODTAREA, ObjectParameter rTARESULTADO)
        {
            var cODPROCESOParameter = cODPROCESO.HasValue ?
                new ObjectParameter("CODPROCESO", cODPROCESO) :
                new ObjectParameter("CODPROCESO", typeof(decimal));
    
            var cODTAREAParameter = cODTAREA.HasValue ?
                new ObjectParameter("CODTAREA", cODTAREA) :
                new ObjectParameter("CODTAREA", typeof(decimal));
    
            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));
    
            var mENSAJEParameter = mENSAJE != null ?
                new ObjectParameter("MENSAJE", mENSAJE) :
                new ObjectParameter("MENSAJE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NUEVO_TRAMITE", cODPROCESOParameter, cODTAREAParameter, cODFUNCIONARIOParameter, mENSAJEParameter, rESPCODTRAMITE, rESPCODTAREA, rTARESULTADO);
        }
    
        public virtual int SP_NUEVO_TRAMITE_REGISTRO(Nullable<decimal> cODPROCESO, Nullable<decimal> cODFUNCIONARIO, string mENSAJE, ObjectParameter rESPCODTRAMITE, ObjectParameter rESPCODTAREA, ObjectParameter rTARESULTADO)
        {
            var cODPROCESOParameter = cODPROCESO.HasValue ?
                new ObjectParameter("CODPROCESO", cODPROCESO) :
                new ObjectParameter("CODPROCESO", typeof(decimal));
    
            var cODFUNCIONARIOParameter = cODFUNCIONARIO.HasValue ?
                new ObjectParameter("CODFUNCIONARIO", cODFUNCIONARIO) :
                new ObjectParameter("CODFUNCIONARIO", typeof(decimal));
    
            var mENSAJEParameter = mENSAJE != null ?
                new ObjectParameter("MENSAJE", mENSAJE) :
                new ObjectParameter("MENSAJE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NUEVO_TRAMITE_REGISTRO", cODPROCESOParameter, cODFUNCIONARIOParameter, mENSAJEParameter, rESPCODTRAMITE, rESPCODTAREA, rTARESULTADO);
        }
    
        public virtual int SP_OBTENER_PROCESO_TAREA(Nullable<decimal> cODTAREA, ObjectParameter rESPCODPROCESO, ObjectParameter rTARESULTADO)
        {
            var cODTAREAParameter = cODTAREA.HasValue ?
                new ObjectParameter("CODTAREA", cODTAREA) :
                new ObjectParameter("CODTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OBTENER_PROCESO_TAREA", cODTAREAParameter, rESPCODPROCESO, rTARESULTADO);
        }
    
        public virtual int SP_SET_ITEMVISITA(Nullable<decimal> iDVISITA, Nullable<decimal> iDITEM, Nullable<decimal> iDTRAMITE, ObjectParameter rTAI)
        {
            var iDVISITAParameter = iDVISITA.HasValue ?
                new ObjectParameter("IDVISITA", iDVISITA) :
                new ObjectParameter("IDVISITA", typeof(decimal));
    
            var iDITEMParameter = iDITEM.HasValue ?
                new ObjectParameter("IDITEM", iDITEM) :
                new ObjectParameter("IDITEM", typeof(decimal));
    
            var iDTRAMITEParameter = iDTRAMITE.HasValue ?
                new ObjectParameter("IDTRAMITE", iDTRAMITE) :
                new ObjectParameter("IDTRAMITE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_ITEMVISITA", iDVISITAParameter, iDITEMParameter, iDTRAMITEParameter, rTAI);
        }
    }
}
